Resources:
  ApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref Application
      Description: Version 1.0
      SourceBundle:
        S3Bucket: ${file(serverless.yml):custom.s3BucketName}
        S3Key: Dockerrun.aws.json