Resources:
    Application:
    Type: 'AWS::ElasticBeanstalk::Application'
    Properties:
      ApplicationName: ${file(serverless.yml):custom.elasticBeanstalkName}
      Description: AWS Elastic Beanstalk Docker Sample Application