Resources:
  # Resources name
  S3BucketResource:
    # Resource Type
    Type: 'AWS::S3::Bucket'
    # Properties Deploy Service
    Properties:
      AccessControl: PublicRead
      BucketName: ${file(serverless.yml):custom.s3BucketName}
      # Set Policy Access
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      # Set Tags Deploy
      Tags:
        - Key: Name
          Value: S3-Bucket-WebApp